version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq

  calendar:
    build:
      dockerfile: ./build/calendar/Dockerfile
      context: ./..
    environment:
      - CONFIG_FILE=/etc/calendar/config.toml
    volumes:
      - ${CALENDAR_CONFIG_DIR}:/etc/calendar/
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z postgres 5432; do
          echo "waiting for services"
          sleep 5
        done
        echo "waiting for migrations..."
        sleep 5
        /opt/calendar/calendar-app -config=/etc/calendar/config.toml
    restart: always
    container_name: calendar
    networks:
      - postgres
    depends_on:
      - postgres

  calendar_migrator:
    build:
      dockerfile: ./build/calendar_migrator/Dockerfile
      context: ./..
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z postgres 5432; do
          echo "waiting for services"
          sleep 1
        done
        echo "apply migrations..."
        /bin/goose -dir ./migrations up
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:postgres@postgres:5432/calendar?sslmode=disable
    container_name: calendar_migrator
    networks:
      - postgres
    depends_on:
      - postgres

  calendar_scheduler:
    build:
      dockerfile: ./build/calendar_scheduler/Dockerfile
      context: ./..
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z postgres 5432 && nc -z rabbitmq 5672; do
          echo "waiting for services"
          sleep 5
        done
        echo "waiting for migrations..."
        sleep 5
        /opt/calendar/calendar-scheduler-app -config=/etc/calendar/config_scheduler.toml
    volumes:
      - ${CALENDAR_CONFIG_DIR}:/etc/calendar/
    restart: always
    container_name: calendar_scheduler
    networks:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  calendar_sender:
    build:
      dockerfile: ./build/calendar_sender/Dockerfile
      context: ./..
    volumes:
      - ${CALENDAR_CONFIG_DIR}:/etc/calendar/
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z postgres 5432 && nc -z rabbitmq 5672; do
          echo "waiting for services"
          sleep 5
        done
        echo "waiting for migrations..."
        sleep 5
        /opt/calendar/calendar-sender-app -config=/etc/calendar/config_sender.toml
    restart: always
    container_name: calendar_sender
    networks:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  integration_tests:
    build:
      dockerfile: ./tests/Dockerfile
      context: ./..
    restart: "no"
    container_name: integration_tests
    command:
      - /bin/sh
      - -c
      - |
        wait-go -wait "postgres:5432" -interval 5 -command "echo \"services are up and running\""
        echo "waiting for migrations..."
        sleep 5
        go test -tags=integration ./...
    environment:
      - TEST_DATASOURCE=postgres://postgres:postgres@postgres:5432/calendar?sslmode=disable
    networks:
      - postgres
    depends_on:
      - calendar
      - calendar_migrator
      - calendar_scheduler
      - calendar_sender

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge
