# Example config

[logger]
level = "info"

[server]
host = "localhost"
port = 3000
gateway_port = 3001
shutdown_timeout = 3000 # ms

[database]
memory_storage = "sql" # available storages: `inmemory` | `sql`
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
db_name = "calendar"
ssl_mode = "disable"
db_timeout = 3000 # ms
max_connections = 5
