# Example config

[logger]
level = "info"

[server]
host = "localhost"
port = 3000
shutdown_timeout = 3000

[database]
memory_storage = "inmemory" # available storages: `inmemory` | `sql`
host = "localhost"
port = 5432
username = "postgress"
password = "postgres"
db_name = "calendar"
ssl_mode = "disable"
db_timeout = 3000
max_connections = 5
