# Example config

[logger]
level = "info"

[scheduler]
scan_period = 1 # scan db every minute, setting to bigger period results in ineffective scheduler
delete_period = 525600 # delete events happened 60 * 24 * 365 minutes ago (1 year)
start_immediate = true # start immediately or wait for `scan_period` minutes

[database]
storage_type = "sql" # for scheduler only sql database is available
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
db_name = "calendar"
ssl_mode = "disable"
db_timeout = 3000 # ms
max_connections = 5

[rabbitmq]
host = "localhost"
port = 5672
username = "admin"
password = "admin"
exchange = "calendar-test"
exchange_type = "direct"
queue = "calendar-test-queue"
consumer_tag = "calendar-consumer"
binding_key = "calendar-test-key"
reliable = true # log message acknowledgements
persistent = true # persist data (both messages and structures)
